// Code generated by "juicecli impl --type Interface --output interface_impl.go"; DO NOT EDIT.

package testcase

import (
	"context"
	"database/sql"
	"github.com/eatmoreapple/juice"
)

type InterfaceImpl struct{}

func (i InterfaceImpl) GetUserByID(ctx context.Context, id int64) (arg0 []*User, arg1 error) {
	manager := juice.ManagerFromContext(ctx)
	var iface Interface = i
	executor := juice.NewGenericManager[[]*User](manager).Object(iface.GetUserByID)
	return executor.QueryContext(ctx, id)
}

func (i InterfaceImpl) CreateUser(ctx context.Context, u map[string]*User) (arg0 error) {
	manager := juice.ManagerFromContext(ctx)
	var iface Interface = i
	executor := manager.Object(iface.CreateUser)
	_, err := executor.ExecContext(ctx, u)
	return err
}

func (i InterfaceImpl) DeleteUserByID(ctx context.Context, id int64, name string) (arg0 sql.Result, arg1 error) {
	manager := juice.ManagerFromContext(ctx)
	var iface Interface = i
	executor := manager.Object(iface.DeleteUserByID)
	return executor.ExecContext(ctx, juice.H{"id": int64, "name": string})
}

// NewInterface returns a new Interface.
func NewInterface() Interface {
	return &InterfaceImpl{}
}
