// Code generated by "juice --type Interface --config ./config.xml --namespace main.UserRepository"; DO NOT EDIT.

package testcase

import (
	"context"
	"github.com/eatmoreapple/juice"
	"os/user"
)

type InterfaceImpl struct{}

func (i InterfaceImpl) GetUserByID(ctx context.Context, id int64) (*User, error) {
	manager := juice.ManagerFromContext(ctx)
	var iface Interface = i
	executor := juice.NewGenericManager[*User](manager).Object(iface.GetUserByID)
	return executor.QueryContext(ctx, id)
}

func (i InterfaceImpl) CreateUser(ctx context.Context, u *user.User) error {
	manager := juice.ManagerFromContext(ctx)
	var iface Interface = i
	executor := juice.NewGenericManager[error](manager).Object(iface.CreateUser)
	_, err := executor.ExecContext(ctx, u)
	return err
}

func NewInterface() Interface {
	return &InterfaceImpl{}
}
